### ISSUE TITLE
Private Key And MongoDB Url left in .env file

### ISSUE THREAD

**Issue by Chibueze864** [MohamedAmineALLAF/MERN_Bookstore#3]
In your backend folder, it seems like to exposed your MongoDB Url and private key. It's highly advised to put your.env folder in a gitignore file as it contains very sensitive information that should not be made public

**Comment by Yassin-Aru** [comment]
I will hide them right a way, I just forked the repo and I will create an new pull request right now !

**Comment by Yassin-Aru** [comment]
#5 
I think this is enough

**Comment by faisalnazir7** [comment]
You can mark resolved issues **closed**.
